Do not set url for BaseRedisBroker
taskiq-python/taskiq-redis pull request #40
Opened 2023-08-16 01:15 UTC by igoose1

Closes: #39

2023-08-16 01:16 UTC, igoose1 commented
- [x] I've used pre-commit to run linters,
- [x] Tests are passing.

2023-08-28 10:55 UTC, s3rius requested changes
It looks good to me. But can you please update PR according to the comment?

2023-08-28 10:55 UTC, s3rius commented on tests/test_broker.py
> +    with pytest.raises(TypeError):
I guess this test is not required. Because it will guaranteed to fail.

2023-08-29 09:20 UTC, igoose1 commented
@s3rius, fixed it!

2023-09-01 14:52 UTC, s3rius approved these changes

2023-09-01 14:52 UTC, merged